---
title: "Introduction"
author: "Freddy Hernández"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE, fig.width=20}
knitr::opts_chunk$set(
  collapse= TRUE,
  comment= "##"
  )
```

# cub distribution

```{r}
require(cubm)
set.seed(1234)
y <- rcub(n=100, pi=0.15, xi=0.60, m=5)
mod1 <- cub(pi.fo=y ~ 1, xi.fo=~ 1, m=5, optimizer='nlminb')
# Summary table
summary(mod1)
# To obtain the fitted parameters in the appropiate scale
# we need to apply the inverse link function to the fitted parameters
pnorm(mod1$par)

# Using logit link function
mod2 <- cub(pi.fo=y ~ 1, xi.fo=~ 1, m=5, optimizer='nlminb',
            pi.link='logit', xi.link='logit')
# Summary table
summary(mod2)
# To obtain the fitted parameters in the appropiate scale we need
# to apply the inverse link function (logit) to the fitted parameters
1 / (1 + exp(-mod2$par))

# Using DEoptim optimizer, it is slower but it gives good results
mod3 <- cub(pi.fo=y ~ 1, xi.fo=~ 1, m=5,
            optimizer='DEoptim', trace=50, itermax=300)
# Summary table
summary(mod3)
# we need to apply the inverse link function to obtain the parameters
pnorm(mod3$par)
```

